TITLE="Hướng dẫn Lập trình C của Beej"
SUBTITLE=""
AUTHOR='Brian “Beej Jorgensen” Hall (bản dịch tiếng Việt của Duc-Tam Nguyen)'
VERSION_DATE="v0.10.5, Copyright © April 18, 2026"

GUIDE_ID=bgc
BGBSPD_BUILD_DIR?=../../bgbspd

#WEB_IMAGES=$(wildcard img_*.svg)

include $(BGBSPD_BUILD_DIR)/source.make
